
export enum EnumClasse {  
  BALANCO = 'PATRIMONIO_BALANCO',
  SETOR_VENDAS = "SETOR_VENDAS",
  SETOR_PRODUCAO = "SETOR_PRODUCAO",
  MATERIAIS_E_SERVICOS = 'MATERIAIS_E_SERVICOS',
  SETOR_FINANCEIRO = 'SETOR_FINANCEIRO'
}
  
  